name: CI
on: [push, pull_request]
jobs:
  build:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    runs-on: ${{ matrix.os }}
    name: test on ${{ matrix.python }} (${{ matrix.os }}, ${{ matrix.concurrency}})

    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v0
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        pip install --upgrade pip setuptools
        pip install requests-mock
        pip install coveralls
        pip install nose parameterized
        pip install wheel
        pip install twine
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        make test
